import { Customer, Leader, Worker } from "../app/models/user";

export const users: (Leader | Worker | Customer)[] = [
  {
    AccountId: "1",
    Fullname: "John Doe",
    Email: "john.doe@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7890",
    AvatarUrl: "https://example.com/avatar1.png",
    DateOfBirth: "1990-01-01",
    IsDisabled: false,
    DisabledReason: "",
    Role: "3", // Leader
    LeaderId: "LDR001",
  },
  {
    AccountId: "2",
    Fullname: "Jane Smith",
    Email: "jane.smith@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7891",
    AvatarUrl: "https://example.com/avatar2.png",
    DateOfBirth: "1992-02-02",
    IsDisabled: false,
    DisabledReason: "",
    Role: "4", // Worker
    WorkerId: "WRK001",
    LeaderId: "LDR001",
  },
  {
    AccountId: "3",
    Fullname: "Robert Johnson",
    Email: "robert.johnson@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7892",
    AvatarUrl: "https://example.com/avatar3.png",
    DateOfBirth: "1988-03-03",
    IsDisabled: false,
    DisabledReason: "",
    Role: "5", // Customer
    CustomerId: "CST001",
    RoomId: "RM001",
  },
  {
    AccountId: "4",
    Fullname: "Emily Davis",
    Email: "emily.davis@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7893",
    AvatarUrl: "https://example.com/avatar4.png",
    DateOfBirth: "1995-04-04",
    IsDisabled: true,
    DisabledReason: "Account Suspended",
    Role: "3", // Leader
    LeaderId: "LDR002",
  },
  {
    AccountId: "5",
    Fullname: "Michael Brown",
    Email: "michael.brown@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7894",
    AvatarUrl: "https://example.com/avatar5.png",
    DateOfBirth: "1993-05-05",
    IsDisabled: false,
    DisabledReason: "",
    Role: "4", // Worker
    WorkerId: "WRK002",
    LeaderId: "LDR002",
  },
  {
    AccountId: "6",
    Fullname: "Sarah Wilson",
    Email: "sarah.wilson@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7895",
    AvatarUrl: "https://example.com/avatar6.png",
    DateOfBirth: "1985-06-06",
    IsDisabled: false,
    DisabledReason: "",
    Role: "5", // Customer
    CustomerId: "CST002",
    RoomId: "RM002",
  },
  {
    AccountId: "7",
    Fullname: "David Miller",
    Email: "david.miller@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7896",
    AvatarUrl: "https://example.com/avatar7.png",
    DateOfBirth: "1989-07-07",
    IsDisabled: false,
    DisabledReason: "",
    Role: "3", // Leader
    LeaderId: "LDR003",
  },
  {
    AccountId: "8",
    Fullname: "Olivia Moore",
    Email: "olivia.moore@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7897",
    AvatarUrl: "https://example.com/avatar8.png",
    DateOfBirth: "1991-08-08",
    IsDisabled: false,
    DisabledReason: "",
    Role: "4", // Worker
    WorkerId: "WRK003",
    LeaderId: "LDR003",
  },
  {
    AccountId: "9",
    Fullname: "James Taylor",
    Email: "james.taylor@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7898",
    AvatarUrl: "https://example.com/avatar9.png",
    DateOfBirth: "1987-09-09",
    IsDisabled: false,
    DisabledReason: "",
    Role: "5", // Customer
    CustomerId: "CST003",
    RoomId: "RM003",
  },
  {
    AccountId: "10",
    Fullname: "Sophia Anderson",
    Email: "sophia.anderson@example.com",
    Password: "password123",
    PhoneNumber: "123-456-7899",
    AvatarUrl: "https://example.com/avatar10.png",
    DateOfBirth: "1994-10-10",
    IsDisabled: true,
    DisabledReason: "Violation of Terms",
    Role: "4", // Worker
    WorkerId: "WRK004",
    LeaderId: "LDR003",
  },
];
